Dailykart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('search/', include('search.urls')),
    path('kart/', include('Kart.urls')),
    path('order/', include('order.urls')),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('account/', views.user_account, name='account'),
    path('account/edit', views.edit_account, name='edit-account'),
    path('account/change-password', views.change_password, name='change-password'),
    path('account/delete', views.delete_account, name='delete-account'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Kart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_kart, name='view-kart'),
    path('<int:id>', views.update_kart, name='update-kart'),
]

Kart/models.py
from django.db import models
from products.models import Products
from django.contrib.auth import get_user_model
from order.models import Order
# Create your models here.
User = get_user_model()

class CartItem(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, blank=True, null=True)
    kart = models.ForeignKey('Kart', null=True, blank=True, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    line_total = models.DecimalField(default=0, max_digits=50, decimal_places=2)

    def __str__(self):
        return str(self.product.id)


class Kart(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    #item = models.ManyToManyField(CartItem, null=True, blank=True)
    #products = models.ManyToManyField(Products, null=True, blank=True)
    total = models.DecimalField(max_digits=50, decimal_places=2, default=0.00)
    item_count = models.IntegerField(default=0)

    def __str__(self):
        return str(self.id)

templates/_alerts.html
{% if messages %}
{% for message in messages %}
<div id="message" class="container">
    <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
        <strong>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
             Error
            {% else %}
                {{ message.tags|title }}
            {% endif %}
        </strong>
        {{ message }}
    </div>
</div>
{% endfor %}
{% endif %}

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Daily Kart</title>
    <style>
      .dropbtn {
        margin: 7px;
        color: #707B7C;
        cursor: pointer;
       }
        .dropdown-content {
          display: none;
          position: absolute;
          background-color: #f9f9f9;
          min-width: 160px;
          z-index: 1;
        }
        .dropdown-content a {
            color: black;

            text-decoration: none;
            display: block;
        }

        .dropdown-content a:hover {}

        .dropdown:hover .dropdown-content {
            display: block;
        }

        .dropdown:hover .dropbtn {

        }

    </style>
  </head>
<body>

    <!-- Navbar -->
    <div style="margin-bottom: 80px">
    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
  <!--<a class="navbar-brand" href="{% url 'home' %}">Daily Kart</a>-->
     <a href="{% url 'home' %}"> <img src="{% static 'dklogo.png' %}" width="150px" height="60px" style="margin-right: 30px"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">About</a>
      </li>
      {% if user.is_authenticated %}
        <li class="nav-item">
        <div class="dropdown">
        <label class="dropbtn"><img src="{% static 'human.jpeg' %}" width="20px" height="20px"> {{ user.username }}</label>

          <div class="dropdown-content">
            <a class="nav-link" href="{% url 'account' %}">Profile</a>
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </div>
        </div>
        </li>
      {% ifequal user.account.category 'shopkeeper' %}
      {% else %}
      {% ifequal user.account.category 'delivery' %}
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'view-kart' %}"><img src="{% static 'shopping-cart.png' %}" width="20px" height="25px">Cart <span class="badge badge-dark">{{ user.cartitem_set.count }}</span> </a>
      </li>
      {% endifequal %}
      {% endifequal %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'order-list' %}">Orders </a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'register' %}">Sign Up</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
      {% endif %}

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'search-product' %}?q=milk">Milk</a>
          <a class="dropdown-item" href="{% url 'search-product' %}?q=biscuit">Biscuit</a>
          <a class="dropdown-item" href="{% url 'search-product' %}?q=bread">Bread</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'search-product' %}?q=">View all</a>
        </div>
      </li>

    </ul>
    <form method="GET" action="{% url 'search-product' %}" class="form-inline my-auto my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" aria-label="Search" value="{{ request.GET.q }}" required>
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
      </div>

    {% block content %}
    {% endblock content %}

    <!-- footer -->

<footer class="my-auto pt-auto text-muted text-center text-small">
  <HR>
    <p class="mb-1">&copy; 2019-2050 Daily Kart</p>
    <ul class="list-inline">
      <li class="list-inline-item"><a href="{% url 'privacy' %}">Privacy</a></li>
      <li class="list-inline-item"><a href="{% url 'terms' %}">Terms and Condition</a></li>
    </ul>
  </footer>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>